# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_measurement.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15log_measurement.proto\x12\x0flogging_service\"t\n\nLogRequest\x12\x16\n\x0emeasured_sites\x18\x01 \x03(\x05\x12\x15\n\rmeasured_pins\x18\x02 \x03(\t\x12\x0f\n\x07voltage\x18\x03 \x03(\x02\x12\x0f\n\x07\x63urrent\x18\x04 \x03(\x02\x12\x15\n\rin_compliance\x18\x05 \x03(\x08\"\r\n\x0bLogResponse2R\n\x0eLogMeasurement\x12@\n\x03Log\x12\x1b.logging_service.LogRequest\x1a\x1c.logging_service.LogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_measurement_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGREQUEST']._serialized_start=42
  _globals['_LOGREQUEST']._serialized_end=158
  _globals['_LOGRESPONSE']._serialized_start=160
  _globals['_LOGRESPONSE']._serialized_end=173
  _globals['_LOGMEASUREMENT']._serialized_start=175
  _globals['_LOGMEASUREMENT']._serialized_end=257
# @@protoc_insertion_point(module_scope)
