# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import log_measurement_pb2 as log__measurement__pb2


class LogMeasurementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Log = channel.unary_unary(
                '/logging_service.LogMeasurement/Log',
                request_serializer=log__measurement__pb2.LogRequest.SerializeToString,
                response_deserializer=log__measurement__pb2.LogResponse.FromString,
                )


class LogMeasurementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Log(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogMeasurementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Log': grpc.unary_unary_rpc_method_handler(
                    servicer.Log,
                    request_deserializer=log__measurement__pb2.LogRequest.FromString,
                    response_serializer=log__measurement__pb2.LogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logging_service.LogMeasurement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LogMeasurement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/logging_service.LogMeasurement/Log',
            log__measurement__pb2.LogRequest.SerializeToString,
            log__measurement__pb2.LogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
