"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import log_measurement_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class LogMeasurementStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    LogMeasurement: grpc.UnaryUnaryMultiCallable[
        log_measurement_pb2.LogMeasurementRequest,
        log_measurement_pb2.LogMeasurementResponse,
    ]

class LogMeasurementAsyncStub:
    LogMeasurement: grpc.aio.UnaryUnaryMultiCallable[
        log_measurement_pb2.LogMeasurementRequest,
        log_measurement_pb2.LogMeasurementResponse,
    ]

class LogMeasurementServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def LogMeasurement(
        self,
        request: log_measurement_pb2.LogMeasurementRequest,
        context: _ServicerContext,
    ) -> typing.Union[log_measurement_pb2.LogMeasurementResponse, collections.abc.Awaitable[log_measurement_pb2.LogMeasurementResponse]]: ...

def add_LogMeasurementServicer_to_server(servicer: LogMeasurementServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
