"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class LogRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MEASURED_SITES_FIELD_NUMBER: builtins.int
    MEASURED_PINS_FIELD_NUMBER: builtins.int
    VOLTAGE_MEASUREMENTS_FIELD_NUMBER: builtins.int
    CURRENT_MEASUREMENTS_FIELD_NUMBER: builtins.int
    IN_COMPLIANCE_FIELD_NUMBER: builtins.int
    @property
    def measured_sites(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def measured_pins(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def voltage_measurements(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def current_measurements(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def in_compliance(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bool]: ...
    def __init__(
        self,
        *,
        measured_sites: collections.abc.Iterable[builtins.int] | None = ...,
        measured_pins: collections.abc.Iterable[builtins.str] | None = ...,
        voltage_measurements: collections.abc.Iterable[builtins.float] | None = ...,
        current_measurements: collections.abc.Iterable[builtins.float] | None = ...,
        in_compliance: collections.abc.Iterable[builtins.bool] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["current_measurements", b"current_measurements", "in_compliance", b"in_compliance", "measured_pins", b"measured_pins", "measured_sites", b"measured_sites", "voltage_measurements", b"voltage_measurements"]) -> None: ...

global___LogRequest = LogRequest

@typing.final
class LogResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___LogResponse = LogResponse
