# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stubs.log_measurement_pb2 as log__measurement__pb2


class LogMeasurementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogMeasurement = channel.unary_unary(
                '/external_driver_wrapper.LogMeasurement/LogMeasurement',
                request_serializer=log__measurement__pb2.LogMeasurementRequest.SerializeToString,
                response_deserializer=log__measurement__pb2.LogMeasurementResponse.FromString,
                )


class LogMeasurementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LogMeasurement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogMeasurementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogMeasurement': grpc.unary_unary_rpc_method_handler(
                    servicer.LogMeasurement,
                    request_deserializer=log__measurement__pb2.LogMeasurementRequest.FromString,
                    response_serializer=log__measurement__pb2.LogMeasurementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'external_driver_wrapper.LogMeasurement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LogMeasurement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LogMeasurement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/external_driver_wrapper.LogMeasurement/LogMeasurement',
            log__measurement__pb2.LogMeasurementRequest.SerializeToString,
            log__measurement__pb2.LogMeasurementResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
